import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@mui/material/Container";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Header />
        <Container maxWidth="xl">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
